#!/bin/ash
# /dev is mounted by kernel
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

stty -F /dev/ttyS2 sane
stty -F /dev/ttyS2 ispeed 115200
stty -F /dev/ttyS2 ospeed 115200

ash </dev/ttyS2 >/dev/ttyS2 2>&1 &

ash # TODO: replace with an actual program
